import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { TopBar } from '@/components/topBar';
import styles from './layout.module.scss';
import Log from './log/log';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Analytics } from './analytics/analytics';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <TopBar />
          <Tabs defaultValue="log" className={styles.tabs}>
            <TabsList className={styles.tabList}>
              <TabsTrigger value="log">Log</TabsTrigger>
              <TabsTrigger value="calibration">Calibration</TabsTrigger>
              <TabsTrigger value="analytics">Analytics</TabsTrigger>
            </TabsList>
            <TabsContent value="log" className={styles.tabsContent}>
              <Log />
            </TabsContent>
            <TabsContent value="calibration"></TabsContent>
            <TabsContent value="analytics">
              <Analytics />
            </TabsContent>
          </Tabs>
        </ThemeProvider>
      </body>
    </html>
  );
}
